schema_version = "1.0.0"
id = "free_gpt"
version = "1.2.2"
name = "Free Gpt"
tagline = "Automate Blender using GPT without an API key"
maintainer = "haseebahmad295 <quicktiptech@gmail.com>"
type = "add-on"

website = "https://github.com/haseebahmed295/blender-Free-Gpt"

tags = ["Animation", "Object"]

wheels =['./wheels/aiohappyeyeballs-2.4.6-py3-none-any.whl', './wheels/aiohttp-3.11.12-cp311-cp311-win_amd64.whl', './wheels/aiosignal-1.3.2-py2.py3-none-any.whl', './wheels/attrs-25.1.0-py3-none-any.whl', './wheels/Brotli-1.1.0-cp311-cp311-win_amd64.whl', './wheels/certifi-2025.1.31-py3-none-any.whl', './wheels/charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl', './wheels/frozenlist-1.5.0-cp311-cp311-win_amd64.whl', './wheels/g4f-0.4.6.1-py3-none-any.whl', './wheels/idna-3.10-py3-none-any.whl', './wheels/multidict-6.1.0-cp311-cp311-win_amd64.whl', './wheels/nest_asyncio-1.6.0-py3-none-any.whl', './wheels/propcache-0.2.1-cp311-cp311-win_amd64.whl', './wheels/pycryptodome-3.21.0-cp311-abi3-win_amd64.whl', './wheels/requests-2.32.3-py3-none-any.whl', './wheels/urllib3-2.3.0-py3-none-any.whl', './wheels/yarl-1.18.3-cp311-cp311-win_amd64.whl']


blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
network = "Needed to prompt ai  models"



[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
]